### ISSUE TITLE
Repo/Task View Name?

### ISSUE THREAD

**Issue by jhollist** [ropensci/maptools#10]
Was wondering if this was the best name for a task view, given that it is also the name of package?

Perhaps just simply "Mapping" or "Mapping and Cartography" or "Spatial Data Visualization"?

Thoughts?

**Comment by sckott** [comment]
perhaps yeah, it was already changed from `mappingtools` i think  https://github.com/ropensci/maptools/issues/5 - maybe stay away from `Spatial` since there's already a task view named `Spatial`

**Comment by jhollist** [comment]
Perhaps simple is best?  "Mapping"?  

I can update the files and may start to add in some other stuff from the issues.  Won't be able to complete it but can at least get a start.  I'll try to submit a PR in a bit.

**Comment by jhollist** [comment]
Actually looking at this more (my first time playing with ctv), Is it just the MapTools.ctv, makefile, and whiskerit.R that would need updating?

**Comment by sckott** [comment]
just edit https://github.com/ropensci/maptools/blob/master/tools.ctv then run `make` in the repo, or just edit https://github.com/ropensci/maptools/blob/master/tools.ctv and push, then we can compile the changes, the makefile is pretty hacky, sorry

**Comment by jhollist** [comment]
Ah...  I tried to figure it out and lost my changes (not many)...

Done for the night, but may try to get some changes done and pushed tomorrow.

**Comment by sckott** [comment]
@jhollist k, will wait for your changes

**Comment by jhollist** [comment]
Scott, got some changes up on my fork.  Need to look through them some more before PR.  Decided to hold off on any name change stuff mainly because I am not sure what all should be changed...  Maybe tonight for PR?

**Comment by sckott** [comment]
sure, sounds good

**Comment by karthik** [comment]
@jhollist Would you like to join us as an official maintainer?

**Comment by jhollist** [comment]
@karthik Sure.  I haven't worked with the task views prior to this so might need a bit of guidance at first.  

What is the workload like?  I would imagine some up front then a little here and there updating after the first version is complete.

**Comment by karthik** [comment]
@jhollist There will some effort to get this going, but once you pushed the first version, I believe you'll just have maintenance to do from time to time. If you follow the CRANberries twitter account, you'll see new R packages there. If anything sounds mappy, check it out and add it to the issues. One of the maintainers will add it when they find time. There is no pressing need to keep it updated in realtime.
@sckott can say more since he does all of the work on the other taskview.

**Comment by sckott** [comment]
@jhollist it's sort of up to you how much you want to do. the web tech view is a group effort, mostly Leeper and I - once we had the workflow down of going from entering new things to making the readme to making the final ctv, its not much work. 

you do need to use `svn` instead of `git` to submit each update

I have a kind of complicated setup in web tech cause I wanted deep links to each subject area in the github readme, and then I need to manually remove stuff before sending to cran, but that's up to you. 

probably good not to overlap with the Spatial task view http://cran.r-project.org/web/views/Spatial.html

**Comment by jhollist** [comment]
Thanks guys.  

I imagine I won't mess much with the workflow you have set up in the makefile, @sckott .  Perhaps down the line but certainly not as I learn the ropes.  Once we have something pulled together that is ready to push I'll need a bit of help with the `svn` side of things.  Have only use `git`.  

And I agree on limiting the overlap with Spatial. There will be some (`rgdal` comes to mind), but for the most part I think we can keep them separate.

Thanks for letting me help with this.  Looking forward to contributing!

**Comment by sckott** [comment]
@jhollist :rocket:

**Comment by jhollist** [comment]
Last question, then I'll close this issue.  Name change can wait.

Any guidance on best workflow for this?  

1. Keep working on my fork and submit PRs and have you guys accept those?
2. Keep working on my fork and submit PRs, I get push rights and I accept the PRs (probably what I would guess is the best)
3. I get push rights and push directly.  

As for branch to work on, what is best?  I work on github mostly solo and haven't been using branches much, so advice gladly accepted!

**Comment by karthik** [comment]
I'll add you to a team with admin access. So just pull this repo down (no fork necessary) and either push directly if you feel comfortable or push a branch and do a PR. You can merge those yourself or ask one of us to look over before merging.

**Comment by jhollist** [comment]
@karthik Sounds good.  Thanks

**Comment by jsta** [comment]
Any more thoughts on a possible name change? Just landed here searching for the `maptools` package.
